name: Release JARs and native images

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  buildOnLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.3.0
          native-image: true
      - name: Build with Maven
        run: mvn -B clean package -Pnative --file pom.xml
      - name: Copy artifacts
        run: |
          mkdir -p staging
          cp target/Log4j-Scanner staging/Log4j-Scanner-linux-amd64
          cp target/*.jar staging
          cp CHANGELOG.txt staging
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: staging/
      - name: Clean staging
        run: rm -fr staging

  buildOnMacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.3.0
          native-image: true
      - name: Build with Maven
        run: mvn -B clean package -Pnative --file pom.xml
      - name: Copy artifacts
        run: mkdir -p staging && cp target/Log4j-Scanner staging/Log4j-Scanner-mac-amd64
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: staging
      - name: Clean staging
        run: rm -fr staging

  buildOnWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.5.0
      - uses: microsoft/setup-msbuild@v1
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 11
          graalvm-version: 21.3.0
          native-image: true
      - name: Build with Maven
        run: mvn -B clean package -Pnative --file pom.xml
        shell: powershell
      - name: Copy artifacts
        run: mv target/Log4j-Scanner.exe target/Log4j-Scanner-win-amd64.exe
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: warn
          name: package
          path: target/*.exe

  release:
    runs-on: ubuntu-latest
    needs: [buildOnLinux, buildOnMacOS, buildOnWindows]
    steps:
      - name: Download Build results
        uses: actions/download-artifact@v2
        with:
          name: package
          path: releasedResources
      - name: List Resources
        run: ls -R
        working-directory: releasedResources
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: releasedResources/CHANGELOG.txt
          files:
            releasedResources/Log4j-Scanner*