name: Build release

on:
  push:
    branches: [ graalVM-action ]

jobs:
  maven:
    name: Maven and Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload JARs
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: target/*.jar

      - name: Upload Changelog
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: CHANGELOG.MD


  nativeImage:
    name: graalVM ${{ matrix.version }} on OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [ latest ]   # Append other graalVM versions as needed; e.g. [latest, dev, '22.0.0.2']
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          mvn -B clean package -Pnative --file pom.xml

      - name: Rename Unix & Compress
        run: |
          cd target
          mv Log4j-Scanner Log4j-Scanner-native-${{ matrix.os }}
          tar -czvf Log4j-Scanner-${{ matrix.os }}.tar.gz Log4j-Scanner-native-${{ matrix.os }}
        if: runner.os != 'Windows'

      - name: Rename Windows & Compress
        run: |
          cd target
          mv Log4j-Scanner.exe Log4j-Scanner-native-${{ matrix.os }}.exe
          tar -czvf Log4j-Scanner-${{ matrix.os }}.tar.gz Log4j-Scanner-native-${{ matrix.os }}.exe
        if: runner.os == 'Windows'

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: target/*native*


  release:
    runs-on: ubuntu-latest
    needs: [maven, nativeImage]
    steps:
      - name: Download Build results
        uses: actions/download-artifact@v2
        with:
          name: package
          path: releasedResources

      - name: List Resources
        run: ls -R
        working-directory: releasedResources