name: Build release

on:
  push:
    branches: [ graalVM-action ]

jobs:
  maven:
    name: Build Java components and copy Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload JARs
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: target/*.jar

      - name: Upload Changelog
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: CHANGELOG.MD


  nativeImage:
    name: Build native Image with graalVM ${{ matrix.version }} on OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [ latest ]   # Append other graalVM versions as needed; e.g. [latest, dev, '22.0.0.2']
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          mvn -B clean package -Pnative --file pom.xml

      - name: Compress binary
        run: |
          cd target
          tar -czvf Log4j-Scanner-${{ matrix.os }}.tar.gz Log4j-Scanner*

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: target/*.tar.gz
